services:
  app:
    build: .
    container_name: app_nestjs_example
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

  database:
    image: postgres
    container_name: db_nestjs_example
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
